WARNING:root:File resource loader root perfkitbenchmarker/data/ycsb is not a directory.2016-11-03 10:03:01,501 46424913 MainThread INFO     Verbose logging to: /var/folders/qg/jk_flqbd3958k29jqxdvh7640000gn/T/perfkitbenchmarker/runs/46424913/pkb.log2016-11-03 10:03:01,502 46424913 MainThread INFO     PerfKitBenchmarker version: v1.6.0-223-gdf385ff2016-11-03 10:03:01,503 46424913 MainThread INFO     Flag values:--ignore_package_requirements--benchmark_config_file=/Users/enat/PerfKitBenchmarker/iperf.yaml--openstack_network=bechmarks2016-11-03 10:03:01,963 46424913 MainThread WARNING  The key "cloud" was not in the default config, but was in user overrides. This may indicate a typo.2016-11-03 10:03:01,964 46424913 MainThread WARNING  The key "cloud" was not in the default config, but was in user overrides. This may indicate a typo.2016-11-03 10:03:02,011 46424913 MainThread iperf(1/1) INFO     Provisioning resources for benchmark iperf2016-11-03 10:03:02,017 46424913 Thread-1 iperf(1/1) INFO     Testing OpenStack CLI command is installed and working2016-11-03 10:03:02,017 46424913 Thread-1 iperf(1/1) INFO     Running: openstack image list --format json2016-11-03 10:03:04,228 46424913 Thread-1 iperf(1/1) INFO     Ran openstack image list --format json. Got return code (1).STDOUT: STDERR: Ignoring domain related config user_domain_name because identity API version is 2.0Ignoring domain related config user_domain_name because identity API version is 2.0Ignoring domain related config user_domain_name because identity API version is 2.0Expecting to find domain in user - the server could not comply with the request since it is either malformed or otherwise incorrect. The client is assumed to be in error. (HTTP 400) (Request-ID: req-9eb66248-1bff-4d8f-aedf-b4d496f2d974)2016-11-03 10:03:04,230 46424913 Thread-2 iperf(1/1) INFO     Testing OpenStack CLI command is installed and working2016-11-03 10:03:04,230 46424913 Thread-2 iperf(1/1) INFO     Running: openstack image list --format json2016-11-03 10:03:04,299 46424913 MainThread iperf(1/1) ERROR    Exception occurred while calling PrepareVm(<BaseVirtualMachine [ip=None, internal_ip=None]>):Traceback (most recent call last):  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 234, in Run    self.return_value = self.target(*self.args, **self.kwargs)  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 376, in PrepareVm    vm.Create()  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/resource.py", line 160, in Create    self._CreateDependencies()  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/os_virtual_machine.py", line 91, in _CreateDependencies    self._CheckPrerequisites()  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/os_virtual_machine.py", line 158, in _CheckPrerequisites    self._CheckCanaryCommand()  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/os_virtual_machine.py", line 152, in _CheckCanaryCommand    'OpenStack CLI test command failed. Please make sure the OpenStack 'InvalidValue: OpenStack CLI test command failed. Please make sure the OpenStack CLI client is installed and properly configured2016-11-03 10:03:05,888 46424913 Thread-2 iperf(1/1) INFO     Ran openstack image list --format json. Got return code (1).STDOUT: STDERR: Ignoring domain related config user_domain_name because identity API version is 2.0Ignoring domain related config user_domain_name because identity API version is 2.0Ignoring domain related config user_domain_name because identity API version is 2.0Expecting to find domain in user - the server could not comply with the request since it is either malformed or otherwise incorrect. The client is assumed to be in error. (HTTP 400) (Request-ID: req-7d3151c1-b407-416d-b902-a91eeda3a53c)2016-11-03 10:03:05,896 46424913 MainThread iperf(1/1) ERROR    Exception occurred while calling PrepareVm(<BaseVirtualMachine [ip=None, internal_ip=None]>):Traceback (most recent call last):  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 234, in Run    self.return_value = self.target(*self.args, **self.kwargs)  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 376, in PrepareVm    vm.Create()  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/resource.py", line 160, in Create    self._CreateDependencies()  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/os_virtual_machine.py", line 91, in _CreateDependencies    self._CheckPrerequisites()  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/os_virtual_machine.py", line 158, in _CheckPrerequisites    self._CheckCanaryCommand()  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/os_virtual_machine.py", line 152, in _CheckCanaryCommand    'OpenStack CLI test command failed. Please make sure the OpenStack 'InvalidValue: OpenStack CLI test command failed. Please make sure the OpenStack CLI client is installed and properly configured2016-11-03 10:03:05,902 46424913 MainThread iperf(1/1) ERROR    Error during benchmark iperfTraceback (most recent call last):  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 516, in RunBenchmark    DoProvisionPhase(benchmark_name, spec, detailed_timer)  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 352, in DoProvisionPhase    spec.Provision()  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 290, in Provision    vm_util.RunThreaded(self.PrepareVm, self.vms)  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 613, in RunThreaded    max_concurrency=max_concurrent_threads)  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 557, in RunParallelThreads    errors.VmUtil.ThreadException)  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 532, in _RunParallelTasks    '{0}{1}'.format(os.linesep, os.linesep.join(error_strings)))ThreadException: The following exceptions occurred during parallel execution:Exception occurred while calling PrepareVm(<BaseVirtualMachine [ip=None, internal_ip=None]>):Traceback (most recent call last):  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 234, in Run    self.return_value = self.target(*self.args, **self.kwargs)  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 376, in PrepareVm    vm.Create()  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/resource.py", line 160, in Create    self._CreateDependencies()  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/os_virtual_machine.py", line 91, in _CreateDependencies    self._CheckPrerequisites()  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/os_virtual_machine.py", line 158, in _CheckPrerequisites    self._CheckCanaryCommand()  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/os_virtual_machine.py", line 152, in _CheckCanaryCommand    'OpenStack CLI test command failed. Please make sure the OpenStack 'InvalidValue: OpenStack CLI test command failed. Please make sure the OpenStack CLI client is installed and properly configuredException occurred while calling PrepareVm(<BaseVirtualMachine [ip=None, internal_ip=None]>):Traceback (most recent call last):  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 234, in Run    self.return_value = self.target(*self.args, **self.kwargs)  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 376, in PrepareVm    vm.Create()  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/resource.py", line 160, in Create    self._CreateDependencies()  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/os_virtual_machine.py", line 91, in _CreateDependencies    self._CheckPrerequisites()  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/os_virtual_machine.py", line 158, in _CheckPrerequisites    self._CheckCanaryCommand()  File "/Users/enat/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/os_virtual_machine.py", line 152, in _CheckCanaryCommand    'OpenStack CLI test command failed. Please make sure the OpenStack 'InvalidValue: OpenStack CLI test command failed. Please make sure the OpenStack CLI client is installed and properly configured2016-11-03 10:03:05,906 46424913 Thread-6 iperf(1/1) INFO     Running: openstack keypair delete perfkit_key_464249132016-11-03 10:03:07,571 46424913 Thread-6 iperf(1/1) INFO     Ran openstack keypair delete perfkit_key_46424913. Got return code (1).STDOUT: STDERR: Ignoring domain related config user_domain_name because identity API version is 2.0Ignoring domain related config user_domain_name because identity API version is 2.0Ignoring domain related config user_domain_name because identity API version is 2.0Expecting to find domain in user - the server could not comply with the request since it is either malformed or otherwise incorrect. The client is assumed to be in error. (HTTP 400) (Request-ID: req-d92e8831-1c88-440f-abc7-3ce9ec8d0edb)2016-11-03 10:03:07,610 46424913 MainThread iperf(1/1) ERROR    Benchmark 1/1 iperf (UID: iperf0) failed. Execution will continue.2016-11-03 10:03:07,610 46424913 MainThread iperf(1/1) INFO     Benchmark run statuses:---------------------Name   UID     Status---------------------iperf  iperf0  FAILED---------------------Success rate: 0.00% (0/1)2016-11-03 10:03:07,611 46424913 MainThread iperf(1/1) INFO     Complete logs can be found at: /var/folders/qg/jk_flqbd3958k29jqxdvh7640000gn/T/perfkitbenchmarker/runs/46424913/pkb.log